models_file.csv: "models.csv"

apo_dir:  "/data/user/shared_projects/lir_ambra_paper_2020/curation_complexes/lc3b/after_modeller/apo_from_complexes/apo_extracted/"
slim_dir: "/data/user/shared_projects/lir_ambra_paper_2020/curation_complexes/lc3b/fasta_lirs/fasta_files"
#out_dir: "/data/user/shared_projects/cabsdock_data/lir_atg8"
out_dir: "my_test"

cabsdock:
    mc_runs: 300
    k-medoids: 20
    clustering-iterations: 250
    saved_pdb: "A"
    verbose: 4
    dssp_location: "/usr/local/dssp-3.0.10/bin/mkdssp"
