#name of variants file in directory.
variant_csv: "variant.csv"

#PDB input and Output directories
pdb_dir: "/data/raw_data/computational_data/curations_data/tcga_3d/p53/zinc_bound/"

out_dir: "./results" 

cabsflex:
   k-medoids: 20
   verbose: 3
   dssp_location: "/usr/local/dssp-3.0.10/bin/mkdssp"
   run_types:
        #default:
        #    mc-cycles: 50
        #    mc-steps: 50
        #    mc-annealing: 20
        #    random-seed: 10 
        #    ss_def: null
        #    restraints: null
        metal_bound:
            mc-cycles: 50
            mc-steps: 50
            mc-annealing: 20
            random-seed: 10 
            ss_def: null
            restraints: 
               - '--ca-rest-add 179:A 176:A 5.5 1.0'
               - '--ca-rest-add 179:A 238:A 6.6 1.0'
               - '--ca-rest-add 179:A 242:A 8.1 1.0'
               - '--ca-rest-add 176:A 238:A 7.1 1.0'
               - '--ca-rest-add 176:A 242:A 6.5 1.0'
               - '--ca-rest-add 238:A 242:A 6.7 1.0'
        #backbone_flex:
        #    mc-cycles: 50
        #    mc-steps: 50
        #    mc-annealing: 20
        #    random-seed: 10
        #    ss_def: null
        #    restraints: 
        #       - '-f 0'
