models_csv: "models.csv"

apo_dir:  "../../../../../raw_data/computational_data/curations_data/bh3_bcl/bcl2/apo_from_complexes"
slim_dir: "../../../../../raw_data/computational_data/curations_data/bh3_bcl/bcl2/fasta_slim"
out_dir:  "."

cabsdock:
    mc_runs: 200
    k-medoids: 20
    clustering-iterations: 200
    saved_pdb: "A"
    verbose: 4
    dssp_location: "/usr/local/dssp-3.0.10/bin/mkdssp"
    run_types:
        blind:
            ss_def: null
            restraints: null
        blind_2D:
            ss_def: 'HHHHHHHHHHHHHHHHHHHHH'
            restraints: null
                
        D-R:
            ss_def: 'HHHHHHHHHHHHHHHHHHHHH'
            restraints:
                - '--ca-rest-add 102:A 14:PEP 6.5 1.0'
                
