# cabsdocka - A pipeline to perform CABSdock jobs
# Copyright (C) 2021 Matteo Orlandi, Matteo Tiberti, Elena Papaleo
# Computational Structural Biology Lab, Danish Cancer Society Research Center
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import pandas as pd
import numpy as np
import os
from pymol import cmd
from Bio import PDB
from Bio.PDB.PDBIO import PDBIO

configfile: 'config.yaml'

models = pd.read_csv(config['models_csv'], sep=';')
references = pd.read_csv(config['references_csv'])

def get_ss(wildcards):

    this_ss_def = config['cabsdock']['run_types'][wildcards.run_type]['ss_def']

    if this_ss_def is None:
        return ""
    else:
        return f":{this_ss_def}"

def get_restraints(wildcards):

    this_restr = config['cabsdock']['run_types'][wildcards.run_type]['restraints']

    if this_restr is None:
        return ""
    else:
        return " ".join(this_restr)

rule all:
    input:
        expand(
            expand("%s/{peptide_name}/{peptide_name}_{pdb_file}{apo_chain}{slim_chain}_{aa_protein}_{aa_peptide}/{apo_model_name}/{run_type}/output_pdbs/structural_alignment.pse" % config['out_dir'],
                    zip,
                    peptide_name=models['slim_name'],
                    pdb_file=models['apo_structure_source'],
                    apo_chain=models['apo_chain_in_source'],
                    slim_chain=models['slim_chain'],
                    aa_protein=models['apo_seq'],
                    aa_peptide=models['slim_seq'],
                    apo_model_name=models['apo_model_name'],
                    allow_missing=True),
                run_type=list(config['cabsdock']['run_types'].keys()),
                allow_missing=True)

rule cabs_run:
    input:
        apo=lambda wildcards: os.path.join(config['apo_dir'], models[(models['apo_structure_source'] == wildcards.pdb_file) & (models['slim_name'] == wildcards.peptide_name)]['apo_pdb'].to_list()[0]),
        slim=os.path.join(config['slim_dir'], "{peptide_name}_{aa_peptide}.fasta")

    params:
        ss = get_ss,
        restraints = get_restraints,
        random_seed = "" if config['cabsdock']['random_seed'] == False else "-z "+str(config['cabsdock']['random_seed'])

    output:
        expand("%s/{peptide_name}/{peptide_name}_{pdb_file}{apo_chain}{slim_chain}_{aa_protein}_{aa_peptide}/{apo_model_name}/{run_type}/output_pdbs/model_{n}.pdb" % config['out_dir'],
               n=np.arange(config['cabsdock']['k-medoids']),
               allow_missing=True)
    shell:
        """
        working_dir={config[out_dir]}/{wildcards.peptide_name}/{wildcards.peptide_name}_{wildcards.pdb_file}{wildcards.apo_chain}{wildcards.slim_chain}_{wildcards.aa_protein}_{wildcards.aa_peptide}/{wildcards.apo_model_name}/{wildcards.run_type}

        cp {input.apo} $working_dir/
        cp {input.slim} $working_dir/

        cd $working_dir

        cat <<EOF > README
This directory contains a CABS-dock run to model the structure of a complex
between a SLIM peptide and a protein:

    apo structure: {wildcards.pdb_file}, apo_chain {wildcards.apo_chain}, {wildcards.aa_protein}
    slim fasta: {wildcards.peptide_name}, slim_chain {wildcards.slim_chain}, {wildcards.aa_peptide}
    run type: {wildcards.run_type}

This has been performed by running the
run.sh script:

    bash run.sh

a log file called "CABS.log" contaning the output of CABS-dock has also
been written.
EOF

        cat <<"EOF" > run.sh
export slim_seq=$(tail -n 1 $(basename {input.slim}))
export apo_file=$(basename {input.apo})

CABSdock\\
    -i $apo_file\\
    -p $slim_seq{params.ss}\\
    -y {config[cabsdock][mc_runs]}\\
    -k {config[cabsdock][k-medoids]}\\
    --clustering-iterations {config[cabsdock][clustering-iterations]}\\
    {params.random_seed}\\
    {params.restraints}\\
    -A\\
    -o {config[cabsdock][saved_pdb]}\\
    -v {config[cabsdock][verbose]}\\
    --dssp-command {config[cabsdock][dssp_location]}\\
    --log
EOF

        bash run.sh
        """

rule pymol_aln:
    input:
        ref=expand("references/{pdb_ref}", pdb_ref=references["references"]),
        mod=expand("%s/{peptide_name}/{peptide_name}_{pdb_file}{apo_chain}{slim_chain}_{aa_protein}_{aa_peptide}/{apo_model_name}/{run_type}/output_pdbs/model_{n}.pdb" % config['out_dir'], n=np.arange(config['cabsdock']['k-medoids']), allow_missing=True)
    output:
        aln="%s/{peptide_name}/{peptide_name}_{pdb_file}{apo_chain}{slim_chain}_{aa_protein}_{aa_peptide}/{apo_model_name}/{run_type}/output_pdbs/structural_alignment.pse" % config['out_dir']
    run:
        ref_list=[]
        model_list=[]
        for ref in input.ref:
            cmd.load(ref, os.path.basename(ref))
            ref_list.append(os.path.basename(ref))
        for mod in input.mod:
             cmd.load(mod, os.path.basename(mod))
             model_list.append(os.path.basename(mod))
        tot_list=ref_list+model_list
        parser = PDB.PDBParser()
        io = PDBIO()
        structure = parser.get_structure(config["align_ref"], config["align_ref"])
        pdb_chains = structure.get_chains()
        for chain in pdb_chains:
            if len(list(structure[0].get_chains())) > 1:
                if chain.get_id() == config["align_ref_protein_id"]:
                    io.set_structure(chain)
                    ref_single_chain=structure.get_id()[:-4]+"_"+chain.get_id()+".pdb"
                    io.save(ref_single_chain)
                    cmd.load(ref_single_chain, os.path.basename(ref_single_chain))
            else:
                ref_single_chain=config["align_ref"]
                cmd.load(ref_single_chain, os.path.basename(ref_single_chain))
        for k in range(len(tot_list)):
            cmd.align(tot_list[k], os.path.basename(ref_single_chain))
        with open(wildcards.peptide_name+"/"+wildcards.peptide_name+"_"+wildcards.pdb_file+""+wildcards.apo_chain+""+wildcards.slim_chain+"_"+wildcards.aa_protein+"_"+wildcards.aa_peptide+"/"+wildcards.apo_model_name+"/"+wildcards.run_type+"/README", "a") as readme:
            readme.write("\n")
            readme.write("The output_pdbs/ folder contains the output models and a .pse file with the structural alignment of the models and the reference structures.") 
        cmd.save(output.aln)
                                                               
